### ISSUE TITLE
Add option for custom fd command args

### ISSUE THREAD

**Issue by jeffwillette** [nabezokodaikon/ddu-source-file_fd#1]
Hi. This plugin is great and I find it works much faster than the `file_rec` ddu plugin on remote filesystems with sshfs.

One problem I have is that the standard argument of depth 1 is too restrictive and I would like to be able to search for deeper files. Is it possible to add `sourceOptions` setting where we can override the default `fd` command?

https://github.com/nabezokodaikon/ddu-source-file_fd/blob/main/denops/%40ddu-sources/file_fd.ts#L46

**Comment by nabezokodaikon** [comment]
Thank you. Merged.

**Comment by nabezokodaikon** [comment]
I noticed later that you
Do you use in ddu-ui-ff?
I created this plugin for use with ddu-ui-filer.
If you use it with ddu-ui-ff, I recommend using ddu-source-file_external.

**Comment by jeffwillette** [comment]
ok, but I am curious what the difference is? Why would ddu-source-file_external be a better choice than this?

**Comment by nabezokodaikon** [comment]
You can specify the command itself yourself, for example
 https://github.com/matsui54/ddu-source-file_external/blob/dd6f892c0a2b2d18c44f67b0b805948bc714cfd8/doc/ddu-source-file_external.txt#L32
